### ISSUE TITLE
02 par contre...

### ISSUE THREAD

**Issue by JeffAbrahamson** [Killy85/MachineLearningExercises#3]
Tu n'as pas vraiment expliqué ce que tu faisais dans `02/`.  En outre,

```╭╴ (master=) [virt]╶╮
╰ vagrant@ubuntu-xenial:02 $ python gradient_descent_w_scikit.py 
Traceback (most recent call last):
  File "gradient_descent_w_scikit.py", line 7, in <module>
    df = pd.read_csv("exercices/01/Consumo_cerveja.csv") 
  File "/home/vagrant/venv/lib/python3.5/site-packages/pandas/io/parsers.py", line 702, in parser_f
    return _read(filepath_or_buffer, kwds)
  File "/home/vagrant/venv/lib/python3.5/site-packages/pandas/io/parsers.py", line 429, in _read
    parser = TextFileReader(filepath_or_buffer, **kwds)
  File "/home/vagrant/venv/lib/python3.5/site-packages/pandas/io/parsers.py", line 895, in __init__
    self._make_engine(self.engine)
  File "/home/vagrant/venv/lib/python3.5/site-packages/pandas/io/parsers.py", line 1122, in _make_engine
    self._engine = CParserWrapper(self.f, **self.options)
  File "/home/vagrant/venv/lib/python3.5/site-packages/pandas/io/parsers.py", line 1853, in __init__
    self._reader = parsers.TextReader(src, **kwds)
  File "pandas/_libs/parsers.pyx", line 387, in pandas._libs.parsers.TextReader.__cinit__
  File "pandas/_libs/parsers.pyx", line 705, in pandas._libs.parsers.TextReader._setup_parser_source
FileNotFoundError: [Errno 2] File b'exercices/01/Consumo_cerveja.csv' does not exist: b'exercices/01/Consumo_cerveja.csv'
╭╴ (master=) [virt]╶╮
╰ 1, vagrant@ubuntu-xenial:02 $ 
```

**Comment by Killy85** [comment]
Thanks for the feedback!

This has been corrected by commit e0e1b3fa68422f9ca813fb5a00d21c957717c9de 

It was a file forgotten but present on my machine.

Sorry for the inconvenience.
